2016-02-26 23:48:27,326 INFO:             errors [in app.py:32]
2016-02-26 23:49:24,857 ERROR:             Exception on /v1/ocr [POST] [in /home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2016-02-26 23:50:08,341 ERROR:             Exception on /v1/ocr [POST] [in /home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2016-02-26 23:51:22,882 ERROR:             Exception on /v1/ocr [POST] [in /home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2016-02-26 23:51:48,489 ERROR:             Exception on /ocr [POST] [in /home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2016-02-26 23:52:56,754 ERROR:             Exception on /v1/ocr [POST] [in /home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2016-02-26 23:53:16,112 ERROR:             Exception on /v1/ocr [POST] [in /home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2016-02-26 23:53:30,712 INFO:             errors [in app.py:32]
2016-02-26 23:54:37,620 ERROR:             Exception on /v1/ocr [POST] [in /home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2016-02-27 00:00:03,975 ERROR:             Exception on /v1/ocr [POST] [in /home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/home/jgooch/env/local/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2016-02-27 00:00:11,498 INFO:             errors [in app.py:51]
2016-02-27 19:12:31,946 INFO:             errors [in app.py:51]
